spring:
  profiles:
    active: development

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql:replication://${PETCLINIC_PRIMARY_DB_USER_NAME}:${PETCLINIC_PRIMARY_DB_USER_PASSWORD}@${PETCLINIC_PRIMARY_DB_HOST_URL},${PETCLINIC_SECONDARY_DB_USER_NAME}:${PETCLINIC_SECONDARY_DB_USER_PASSWORD}@${PETCLINIC_SECONDARY_DB_HOST_URL}/${PETCLINIC_PRIMARY_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowMasterDownConnections=true&allowSlavesDownConnections=true"
  flyway:
    enabled: true
    user: ${PETCLINIC_PRIMARY_DB_USER_NAME}
    password: ${PETCLINIC_PRIMARY_DB_USER_PASSWORD}
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  servlet:
    encoding:
      force: true
      charset: utf-8


---
spring:
  profiles: development


---
spring:
  profiles: test
  datasource:
    url: "jdbc:mysql:replication//${PETCLINIC_TEST_DB_USER_NAME}:${PETCLINIC_TEST_DB_USER_PASSWORD}@${PETCLINIC_TEST_DB_HOST_URL},${PETCLINIC_TEST_DB_USER_NAME}:${PETCLINIC_TEST_DB_USER_PASSWORD}@${PETCLINIC_TEST_DB_HOST_URL}/${PETCLINIC_TEST_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowMasterDownConnections=true&allowSlavesDownConnections=true"
  jpa:
    hibernate:
      ddl-auto: create

---
spring:
  profiles: production
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
