spring:
  profiles:
    active: development
  banner:
    location: classpath:banner.txt

  datasource:
    primary:
      jdbc-url: "jdbc:mysql://${PETCLINIC_PRIMARY_DB_HOST_URL}/${PETCLINIC_PRIMARY_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul"
      username: ${PETCLINIC_PRIMARY_DB_USER_NAME}
      password: ${PETCLINIC_PRIMARY_DB_USER_PASSWORD}
      validation-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: "jdbc:mysql://${PETCLINIC_SECONDARY_DB_HOST_URL}/${PETCLINIC_SECONDARY_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul"
      username: ${PETCLINIC_SECONDARY_DB_USER_NAME}
      password: ${PETCLINIC_SECONDARY_DB_USER_PASSWORD}
      validation-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    user: ${PETCLINIC_PRIMARY_DB_USER_NAME}
    password: ${PETCLINIC_PRIMARY_DB_USER_PASSWORD}
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  servlet:
    encoding:
      force: true
      charset: utf-8


---
spring:
  profiles: development


---
spring:
  profiles: test
  datasource:
    url: "jdbc:mysql://${PETCLINIC_TEST_DB_USER_NAME}:${PETCLINIC_TEST_DB_USER_PASSWORD}@${PETCLINIC_TEST_DB_HOST_URL}/${PETCLINIC_TEST_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul"
  jpa:
    hibernate:
      ddl-auto: create

---
spring:
  profiles: production
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
