version: "3.8"
services:
  primary:
    image: mysql:5.7
    environment:
      MYSQL_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'petclinic'
    volumes:
      - ./mysql/primary/config:/etc/mysql/conf.d
      - ./mysql/primary/script:/docker-entrypoint-initdb.d
#      - /opt/persistence/mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - new

  secondary:
    image: mysql:5.7
    environment:
      MYSQL_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'petclinic'
    volumes:
      - ./mysql/secondary/config:/etc/mysql/conf.d
      - ./mysql/secondary/script:/docker-entrypoint-initdb.d
#      - /opt/persistence/secondary_mysql:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - new

  mysql_configure:
    image: mysql:5.7
    volumes:
      - ./start_secondary.sh:/tmp/start_secondary.sh
    entrypoint: ["/bin/bash", "-x", "/tmp/start_secondary.sh"]
    networks:
      - new


networks:
  new: